
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 07 10:36:39 CEST 2012
//----------------------------------------------------

package org.cpntools.grader.model.btl.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int GEQ = 27;
  public static final int AND = 20;
  public static final int FAILURE = 17;
  public static final int FINALLY = 30;
  public static final int PLUS = 19;
  public static final int RPAREN = 3;
  public static final int EQUAL = 28;
  public static final int STAR = 14;
  public static final int LPAREN3 = 6;
  public static final int NOT = 13;
  public static final int LPAREN2 = 4;
  public static final int GREATER = 25;
  public static final int TRUE = 15;
  public static final int LPAREN = 2;
  public static final int ID = 32;
  public static final int NUMBER = 33;
  public static final int EOF = 0;
  public static final int STEP = 11;
  public static final int TIME = 21;
  public static final int ADD = 23;
  public static final int MINUS = 18;
  public static final int FALSE = 16;
  public static final int DOT = 29;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int LEQ = 26;
  public static final int RPAREN3 = 7;
  public static final int RPAREN2 = 5;
  public static final int GUARD = 10;
  public static final int BAR = 8;
  public static final int GUARDSTEP = 12;
  public static final int NEXT = 9;
  public static final int FINALLYGUARD = 31;
  public static final int LESS = 24;
}

