
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 27 18:23:41 CEST 2012
//----------------------------------------------------

package org.cpntools.grader.model.btl.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int GEQ = 23;
  public static final int AND = 19;
  public static final int FINALLY = 26;
  public static final int PLUS = 18;
  public static final int RPAREN = 3;
  public static final int EQUAL = 24;
  public static final int STAR = 14;
  public static final int LPAREN3 = 6;
  public static final int NOT = 13;
  public static final int LPAREN2 = 4;
  public static final int GREATER = 21;
  public static final int TRUE = 15;
  public static final int LPAREN = 2;
  public static final int ID = 28;
  public static final int NUMBER = 29;
  public static final int EOF = 0;
  public static final int STEP = 11;
  public static final int MINUS = 17;
  public static final int FALSE = 16;
  public static final int DOT = 25;
  public static final int error = 1;
  public static final int LEQ = 22;
  public static final int RPAREN3 = 7;
  public static final int RPAREN2 = 5;
  public static final int GUARD = 10;
  public static final int BAR = 8;
  public static final int GUARDSTEP = 12;
  public static final int NEXT = 9;
  public static final int FINALLYGUARD = 27;
  public static final int LESS = 20;
}

