
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 20 10:05:22 CET 2011
//----------------------------------------------------

package org.cpntools.algorithms.translator;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int IS = 16;
  public static final int ELSE = 19;
  public static final int RPAREN = 26;
  public static final int INT = 3;
  public static final int THEN = 21;
  public static final int ENDIF = 20;
  public static final int CHAR = 32;
  public static final int IN = 17;
  public static final int WHILE = 8;
  public static final int ALL = 13;
  public static final int LOCK = 6;
  public static final int ENDWHILE = 9;
  public static final int NOT = 5;
  public static final int RETURN = 24;
  public static final int IF = 18;
  public static final int LPAREN = 25;
  public static final int ID = 31;
  public static final int DO = 10;
  public static final int COMMA = 29;
  public static final int PARALLEL = 28;
  public static final int EOF = 0;
  public static final int UNLOCK = 7;
  public static final int ENDPROC = 15;
  public static final int NEWLINE = 30;
  public static final int error = 1;
  public static final int DOT = 4;
  public static final int PROC = 14;
  public static final int ASSIGN = 27;
  public static final int UNTIL = 23;
  public static final int BOOL = 2;
  public static final int FOR = 11;
  public static final int REPEAT = 22;
  public static final int ENDFOR = 12;
}

